modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = ""
license = "LGPL-3.0-only"

[[mods]]
modId = "wood_you_dye"
version = "${version}"
displayName = "Wood You Dye"
displayURL = ""
authors = [
    "Siuolplex"
]
description = '''
A Mod thats all about dyable wooden planks!
'''
logoFile = "icon.png"

[[dependencies.wood_you_dye]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wood_you_dye]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="wood_you_dye.mixins.json"

[[mixins]]
config="wood_you_dye.forge.mixins.json"